name: (5.x) Build packages (on push)

# This workflow runs when any of the following occur:
# - On push

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build-workflow:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/5_builderpackage_common_utils.yml
    secrets: inherit
    with:
      id: ${{ github.ref }}