name: (5.x) Run Gradle check

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - "src/**"
      - "*.gradle"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle-check:
    if: ${{ !github.event.pull_request.draft }}
    runs-on:
      - codebuild-github-actions-codebuild-runner-indexer-amd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Run Gradle check
        run: ./gradlew check

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-results
          overwrite: 'true'
          path: build/test-results/
